jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "actions/setup-java@v3"
      with:
        cache: "maven"
        distribution: "temurin"
        java-version: "17"
    - run: "mvn -B package --file pom.xml"
on: [
  "push"
]
